# Generated by Django 4.2.2 on 2023-07-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreviews_model',
            name='author',
            field=models.CharField(default='Anonymus', max_length=50),
        ),
    ]
