# Generated by Django 4.2.2 on 2023-07-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_bookreviews_model_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreviews_model',
            name='author',
            field=models.CharField(max_length=50),
        ),
    ]
