# Generated by Django 4.2.2 on 2023-07-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_profile_delete_profile_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mob',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
