# Generated by Django 4.2.2 on 2023-07-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreviews_model',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
