# Generated by Django 4.2.2 on 2023-07-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_bookreviews_model_ispublic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='Interests',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
